POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Binary Search",
    "author": "Khoi",
    "url": "https://example.com",
    "likes": "9669",
    "user_id": "612f8f20159bf40d387b5b3c"
}

###
GET http://localhost:3003/api/blogs

###
DELETE http://localhost:3003/api/blogs/6128c84560ddba4e08461f1b
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "yourdada",
    "name": "Khoi",
    "password": "secret"
}
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "yourmama",
    "name": "Kha",
    "password": "123"
}