GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Postman is good for testing REST API",
    "important": true
}
###
PUT http://localhost:3001/api/notes/6124605a8f8c961f509e87c8
Content-Type: application/json

{
    "content": "PUT test",
    "important": true,
    "id": 14
}
###
DELETE http://localhost:3001/api/notes/6124605a8f8c961f509e87c8

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "",
    "important": true
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Testing toJSON method",
    "important": false,
    "userId": "612cc06b66abe809d031a431"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "notes": [],
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "root",
    "password": "salainen"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "root",
    "password": "salainen"
}
###
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYxMmNjMDZiNjZhYmU4MDlkMDMxYTQzMSIsImlhdCI6MTYzMDQ3MDY1MH0.V_Zqp03CVYrlJbg3JsdI9fvuG06Y6DF_3E4Qc7qWg3s

{
    "content": "Wish you were oke oke",
    "important": true
}
